title = "Config for the Browser Extension MV3 Other Node"

[node]
detect-drivers = false

[[node.driver-configuration]]
display-name = "browser_extension_mv3-other"
stereotype = '{"browserName":"chrome", "nodename:applicationName":"browser_extension_mv3-other", "goog:chromeOptions": {"args":["profile-directory=Profile 2", "user-data-dir=C:/Users/admin/AppData/Local/Google/Chrome/User Data"]}}'
max-sessions = 1