title = "Config for the Windows Agent Node"

[node]
detect-drivers = false

[[node.driver-configuration]]
display-name = "windows_10_agent-other"
stereotype = '{"browserName":"chrome", "nodename:applicationName":"windows_10_agent-other", "goog:chromeOptions": {"args":["profile-directory=Profile 2", "user-data-dir=C:/Users/admin/AppData/Local/Google/Chrome/User Data"]}}'
max-sessions = 1